name: iOS Build & Archive

on:
  push:
    branches:
      - main  # Runs when pushing to main branch

jobs:
  build-ios:
    runs-on: macos-latest  # GitHub-hosted macOS runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Enable CocoaPods
        run: |
          cd ios
          pod install
          cd ..

      - name: Build iOS App
        run: flutter build ios --no-codesign  # Builds iOS app without signing

      - name: Upload iOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-build
          path: build/ios/iphoneos
